server:
    port: 8080

spring:
  application:
    name: authentication
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: 'jdbc:mysql://localhost:3306/authentication_database'
    username: root
    password: 'clientDatabase421!'
    driverClassName: com.mysql.cj.jdbc.Driver
    show_sql: true
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 32
    initial-size: 10
    max-idle: 10
    min-idle: 10
    max-wait: 1000
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  pattern:
    console:%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    com.amazonaws: info
    com.amazonaws.request: info
    org:
      hibernate:
        SQL: info